### ISSUE TITLE
Flathub

### ISSUE THREAD

**Issue by Mailaender** [Xenoveritas/abuse#19]
Hi, I created a Flatpak package at https://github.com/flathub/flathub/pull/3208

**Comment by QmwJlHuSg9pa** [comment]
Hi, I installed v0.9.1 from Flathub (Fedora Silverblue).

There is no sound in-game.

Log shows: `Sound: Disabled (couldn't find the sfx directory /app/share/games/abuse/sfx)`
Indeed, when navigating to: _/var/lib/flatpak/app/com.github.Xenoveritas.abuse/current/active/files/share/games/abuse_, there is no _sfx_ directory to be found.

**Comment by QmwJlHuSg9pa** [comment]
I know what I wrote above sounds like a non-issue (and I have since stumbled upon the Github README), but consider the following:

1. I installed Abuse via the Flathub remote. The Flathub listing does not link to the README file. Instead it leads to the homepage of the original project (whereas Xenoveritas is a fork, correct?), and also the Issues page (which is how I found this very issue).
2. Flatpak applications are not directly editable by the user.
3. The [Flatpak docs mention](https://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories) `XDG_DATA_HOME` as a potential location for user-specific data files.
4. Placing `sfx` within `XDG_DATA_HOME` (i.e. _$HOME/.var/app/com.github.Xenoveritas.abuse/data/sfx_) does not resolve the issue (nor do any variations of hierarchy involving _share/games/abuse/_ directories below _data_ dir).

Is the most practical solution here to patch the Flatpak app to search `XDG_DATA_HOME` for user-supplied data files?

Regardless, the Flatpak listing description should be updated to mention that user intervention is required to complete the game install (it is in no way obvious that _sfx_ and _music_ are not packed-in).
