### ISSUE TITLE
vs2019

### ISSUE THREAD

**Issue by vinay** [Xenoveritas/abuse#8]
do you have notes on how to get the build working with vs2019. i tried with the instructions you have currently, and it fails.

**Comment by Xenoveritas** [comment]
So it looks like Visual Studio 2019 has a new bug that makes one of the macros within matrix.h fail with the most useless error message ever. Apparently the macro was just too big for VS2019. Splitting the macro in two made it build for me.

The instructions should otherwise work: run CMake against the Visual Studio 2019 target, it creates the Visual Studio project files, and then either build them within Visual Studio using the `.sln` file or build them using `MSBuild` on the command line. The instructions kind of gloss over the SDL2 dependencies, I'll try and update them to be clearer.

**Comment by Xenoveritas** [comment]
This now builds in MSVC 2019, as that's what I'm using.
